apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-values
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:R07Wl/ZwlGxizbLEywJjOKR4S0TtkFMB7MpVZs3zIAYGaOzRE7ejE4eae/jHS+DByD5q571AxIXNxY/JrUAFc80EYaIKZtyhcHP9Xp4Fu3Ai0XSkFpBnLoxq0jI2tzWbxxBK4BVwp4S5xU4awj39GdtiM2at,iv:uVJNOIhwEYvRcaWnxh97IPh5w8+5XpgFFRbk0g7MGDc=,tag:NZy0P2paHr6+fnzCpaYa5w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-02-09T03:41:37Z"
  mac: ENC[AES256_GCM,data:RNZPzaDR6H2tc7QyqO9hYmV8Ly+esg2iuYN+Zd4kM5esWkgKJg4O3Joybqa5tYHwsEpuaNGWpthZujK/w+NhRkuGvoEyEjxwqJ+ucshcxz9t9RDuOkH+XGmCuwzp1tbvR4ZIRjPf18yqLScihRiyJku9ICGZwd86cISg3o4ug30=,iv:wK6uloSpFuGsbomvp/QKGJkiUnbw3GAOTugu5gLAEvg=,tag:QXpv9XR8VuPuU7q9KTdXrQ==,type:str]
  pgp:
    - created_at: "2025-02-22T18:16:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/7BG8q7uwF2y5IuLtvtbhnQRJ63pUxrx73Dam0h/y+sKsB
        IrHn8SvBDFnsihrRq8k1z57Z8C/coa5sfs6pcytTK15Nrh3+wkwJXBNfJZ48w8Rb
        s/5LxNthqwSAa5AQnip7vVuFl1GnsJ7dbMFoJnPTWL+TzsttfNkhR2TFdx1oDaho
        O38erZ+OK359qTzqB8UTIWRcEA1PPYIi8hweBociy6Hntvn/mSZcWAbEXfby0AHZ
        ZnyHkiVvuP11VYLTRAXYazjsBKBImZbC0k0+Rskq87++9vOYDvV8h70ry+7JfY9N
        Jzx3ej1kz5/CiCx+vSqH4kaI1ZHAKBkt8PzJ7c7HWLBaXparY60hHxtUvc+mUTpV
        4NSpngd6dNUHwYCMedEv/SdombKDBJ5VoRM5JDRg4z1uRffrRuiNxipRgDiqkYyD
        tknBD2fe/uTjIfuKLtRML5JPzXKIKhXDlWS1YI5SI1Ybn4ZQBGzkD5OXCs7nteV2
        1opi2wnTslvV5gW1sGN2W/0IKvsfRbzfUo2pOXunGHAYLYWgUQl352CzFfIkYM2I
        IyGrKMUYxPv7eBoms1QxtvBd7gI//Ca/Xi6HNoDFryqkKGinocjtKsyXKI8v56CG
        ohbTmb9sLEanRPm0ZbQxUDDV1pWrtOhsuLsOvRJqa8ku8/qXJ8phhm4dWgCml2TS
        XAHkoyX9dmGh5wXkXtNUzvI2cuKlAPMtM0GcA9gwv2TT2CJvgngYLWaYumaI76th
        w1V2lOmuFG+m/xHSH4p5/SbvX+fsFmY4aOgqMPtQXSYjtGRiV2PmS7Le8F1x
        =8bGV
        -----END PGP MESSAGE-----
      fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
