# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
spec:
  targetNamespace: intel
  storageNamespace: flux-system
  releaseName: gpu-device-plugin
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
  dependsOn:
  - name: device-plugin-operator
