apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system/
- calico.yaml
- cert-manager.yaml
- deluge.yaml
- intel.yaml
- istio.yaml
- jellyfin.yaml
- kiali.yaml
- grafana.yaml
- k8s-monitoring.yaml
- local-path-provisioner.yaml
- loki.yaml
- metrics-server.yaml
- mimir.yaml
- node-feature-discovery.yaml
- tailscale.yaml
- tempo.yaml
- secrets/
