apiVersion: v1
kind: Secret
metadata:
  name: wg-config
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    PrivateKey = ${private_key}
    Address = ${address}
    DNS = ${dns}

    [Peer]
    PublicKey = ${public_key}
    AllowedIPs = 0.0.0.0/0, ::/0
    Endpoint = ${endpoint}
