apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  postRenderers:
  - kustomize:
      patches:
      # For compatibility with the Tailscale operator,
      # we need to set the Ingress host to "nextcloud"
      # instead of the default "nextcloud.snow-enigmatic.ts.net".
      - target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: nextcloud
        patch: |
          - op: replace
            path: /spec/rules/0/host
            value: nextcloud
  values:
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - host: nextcloud
      tls:
      - hosts:
        - nextcloud
    nextcloud:
      host: nextcloud.snow-enigmatic.ts.net
