apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-monitoring-values
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    cluster:
      name: homeserv
