apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-values
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    operatorConfig:
      hostname: homeserv
