cluster-config:
  network:
    enabled: true
  dns:
    enabled: true
  ingress:
    enabled: false
  metrics-server:
    enabled: false
  load-balancer:
    enabled: false
  local-storage:
    enabled: false
  gateway:
    enabled: false
