# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: local-path-provisioner
  valuesFrom:
  - kind: ConfigMap
    name: local-path-provisioner-values
    optional: true
  - kind: Secret
    name: local-path-provisioner-values
    optional: true
  values:
    storageClass:
      name: local-path
      defaultClass: true
    nodeSelector:
      kubernetes.io/os: linux
    nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
      - /megamind/k8s/dynamic/local-path-provisioner
