apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: deluge
  name: daemon
spec:
  ports:
  - name: daemon
    port: 58846
    protocol: TCP
    targetPort: 58846
  selector:
    app.kubernetes.io/name: deluge
  type: ClusterIP
