apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: deluge
  name: web
spec:
  ports:
  - name: http
    port: 8112
    protocol: TCP
    targetPort: 8112
  selector:
    app.kubernetes.io/name: deluge
  type: ClusterIP
