apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calico
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: calico
  path: ./manifests
  prune: false
