# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 1h
  chart:
    spec:
      chart: base
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
  valuesFrom:
  - kind: ConfigMap
    name: istio-base-values
    optional: true
  - kind: Secret
    name: istio-base-values
    optional: true
