# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: flux-system
spec:
  releaseName: ztunnel
  interval: 1h
  chart:
    spec:
      chart: ztunnel
      version: 1.27.3
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
  - name: cni
  valuesFrom:
  - kind: ConfigMap
    name: ztunnel-values
    optional: true
  - kind: Secret
    name: ztunnel-values
    optional: true
