apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system/
- configmaps/
- secrets/
- cert-manager.yaml
- deluge.yaml
- grafana.yaml
- intel.yaml
- jellyfin.yaml
- k8s-monitoring.yaml
- local-path-provisioner.yaml
- loki.yaml
- metrics-server.yaml
- mimir.yaml
- node-feature-discovery.yaml
- prowlarr.yaml
- radarr.yaml
- sabnzbd.yaml
- tailscale.yaml
- tempo.yaml
