# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: lgtm
spec:
  driftDetection:
    mode: enabled
  releaseName: mimir
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mimir-distributed
  postRenderers:
  - kustomize:
      patches:
      - patch: |
          - op: add
            path: /spec/ports/1/appProtocol
            value: tcp
        target:
          kind: Service
          name: .*-headless$
      - patch: |
          - op: add
            path: /spec/ports/1/appProtocol
            value: grpc
        target:
          kind: Service
          name: ^.+-(?:alertmanager|compactor|distributor|ingester(-zone.*)?|overrides-exporter|querier|query-frontend|store-gateway(-zone.*))$
      - patch: |
          - op: add
            path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
            value: memberlist
          - op: add
            path: /spec/template/spec/containers/0/ports/-
            value:
              containerPort: 7946
              name: memberlist
              protocol: TCP
        target:
          kind: Deployment
          name: ^.+-query-frontend$
  values:
    nginx:
      enabled: false
    alertManager:
      enabled: false
    ruler:
      enabled: false
    query_scheduler:
      enabled: false
    overrides_exporter:
      enabled: false
    minio:
      enabled: true
    ingester:
      zoneAwareReplication:
        enabled: false
      replicas: 2
    store_gateway:
      zoneAwareReplication:
        enabled: false
      replicas: 1
    querier:
      replicas: 1
    mimir:
      structuredConfig:
        memberlist:
          cluster_label: mimir
        limits:
          max_global_series_per_user: 50000
          max_label_names_per_series: 250
        querier:
          max_concurrent: 1024
        query_scheduler:
          max_outstanding_requests_per_tenant: 0
